-- create signature table 
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'EMLUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'EMLUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'EMLUSER', 'T_RESULTS', 'OUT');

-- generate stored procedure
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE" ('EML', 'PREDICTM', 'EMLUSER', 'SCORE_DIGITS', "SIGNATURE");
