python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_0_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_1_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_2_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_3_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_4_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_5_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_6_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_7_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_8_001.jpg
python /tmp/sample/scripts/img2ascii.py /tmp/sample/test/tf/sample_9_001.jpg
