IMPORT FROM CSV FILE '/tmp/sample/test/dbgen/books/books' INTO BOOKS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY '|'
THREADS 20
BATCH 50000;

IMPORT FROM CSV FILE '/tmp/sample/test/dbgen/customers/customers' INTO CUSTOMERS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY '|'
THREADS 20
BATCH 50000;

IMPORT FROM CSV FILE '/tmp/sample/test/dbgen/transactions/transactions' INTO TRANSACTIONS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY '|'
THREADS 20
BATCH 200000;
